# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=500)),
                ('profile_picture', models.ImageField(upload_to=team.models.profile_picture_path)),
            ],
        ),
    ]
