# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20160331_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
