# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20160331_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
